# Generated by Django 4.2 on 2023-04-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_certificate_contactprofile_media_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
